apiVersion: template.openshift.io/v1
kind: Template
metadata: {}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations: null
    creationTimestamp: null
    labels:
      shared: "true"
    name: nginx-120-image-latest
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/rhscl/nginx-120-rhel7:1-47.1661531726
      from:
        kind: DockerImage
        name: registry.redhat.io/rhscl/nginx-120-rhel7:1-47.1661531726
      generation: null
      importPolicy: {}
      name: "1"
      referencePolicy:
        type: "Local"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    labels:
      shared: "true"
    name: ride-vips-adapter-nginx-rev-proxy-image
  spec:
    lookupPolicy:
      local: false
    tags: []
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ride-vips-adapter-nginx-proxy-build
    labels:
      name: ride-vips-adapter-nginx-proxy-build
  spec:
    triggers:
      - type: ConfigChange
    source:
      dockerfile: |
        FROM nginx-120
        CMD ["nginx", "-c", "/tmp/nginx.conf",  "-g", "daemon off;"]
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: ImageStreamTag       
          name: nginx-120-image-latest:1
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: 'ride-vips-adapter-nginx-rev-proxy-image:1'