name: Build and Push Image for PR

on:
  pull_request:
    types: [opened, reopened,edited,synchronize]
    branches-ignore:   
      - 'main'
      - 'master'
      # - 'release**'


jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      build_config_name: "ride-vips-adapter-nginx-proxy-build-v2"
      base_image_tag: "1"
      PR_NUMBER: ${{ github.event.number }}
      PR_IMAGE_STREAM_TAG: pr-build-${{ github.sha}}


    steps:
      # - name: Merge with PR branch
      #   run: |
      #     git clone "https://github.com/bcgov/rsbc-ride-adapters"
      #     git config --global user.email "ride_vips_actions@gov.bc.ca"
      #     git config --global user.name "ride_vips_actions"
      #     git config --global pull.rebase true
      #     cd rsbc-ride-adapters
      #     git fetch
      #     git branch -a
      #     git checkout $GITHUB_HEAD_REF      
      #     git checkout $GITHUB_BASE_REF  
      #     git merge $GITHUB_HEAD_REF 
      #     git checkout -b pr-${{ env.PR_NUMBER }}-branch
      #     git remote add testbranch https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git push -u testbranch pr-${{ env.PR_NUMBER }}-branch

      # - name: Checkout repository
      #   uses: actions/checkout@v3        
      #   with:
      #     ref: pr-${{ env.PR_NUMBER }}-branch
      # - name: Authenticate and set context
      #   uses: redhat-actions/oc-login@v1.1.2
      #   with:
      #     openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      #     openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      #     namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      # - name: Apply Build Yaml
      #   run: |
      #     cd rsbc_df_vips_adapter_gateway/github_actions_yamls
      #     oc process -f revproxy_build_template.yml --param-file revproxy_build_params.yml --param OUTPUT_IMAGE_STREAM_TAG=pr-build-$GITHUB_SHA | oc apply -f -
      # - name: Start the build and push
      #   run: |
      #     oc start-build ${{ env.build_config_name }} --follow --wait
      # - name: Delete Temp Branch
      #   run: |
      #     git clone "https://github.com/bcgov/rsbc-ride-adapters"
      #     git config --global user.email "ride_vips_actions@gov.bc.ca"
      #     git config --global user.name "ride_vips_actions"
      #     git config --global pull.rebase true
      #     cd rsbc-ride-adapters
      #     git fetch
      #     git remote add testbranch https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git push -d testbranch pr-${{ env.PR_NUMBER }}-branch
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      # - name: Update Image tag for PR deploy
      #   uses: mikefarah/yq@v4.28.1
      #   with:
      #     cmd: yq eval -i '.images[0].newTag = "pr-build-${{env.PR_IMAGE_STREAM_TAG}}"' 'rsbc_df_vips_adapter_gateway/kustomization_yaml_sample/kustomization.yml'
      # - name: Check Changed value
      #   run: |
      #     cat rsbc_df_vips_adapter_gateway/kustomization_yaml_sample/kustomization.yml
        - name: Checkout Gitops repository
          uses: actions/checkout@v3
          with:
            repository: bcgov-c/tenant-gitops-be5301
            ref: deployment/rsbc-ride-vips-adapter
            token: ${{ secrets.GITOPS_GITHUB_TOKEN }}
        - name: Update Image tag for PR deploy
          uses: mikefarah/yq@v4.28.1
          with:
            cmd: yq eval -i '.images[0].newTag = "pr-build-${{env.PR_IMAGE_STREAM_TAG}}"' 'ride_vips_adapter/overlays/pr/kustomization.yaml'
        - name: Update name suffix for PR deploy
          uses: mikefarah/yq@v4.28.1
          with:
            cmd: yq eval -i '.nameSuffix = "-pr-${{env.PR_NUMBER}}"' 'ride_vips_adapter/overlays/pr/kustomization.yaml'
        - name: Check Changed value
          run: |
            cat ride_vips_adapter/overlays/pr/kustomization.yaml
        