name: CI Checks for build

on:
  push:
    branches-ignore:   
      - 'release**'
      - 'feature/ride294_buildpush'

jobs:
  test-build-image:
    runs-on: ubuntu-latest
    env:
      build_config_name: "ride-vips-adapter-nginx-proxy-build"
      image_stream_name: " ride-vips-adapter-nginx-rev-proxy-image"
      image_tags: "dev"
      base_image_tag: "1"