name: Merge PR to Release Branch

on:
  # push:
  #   branches:   
  #     - 'release**'
  pull_request:
    types: [closed]
    branches:   
      - 'release**'

jobs:
  build-image:
    name: Build and Push the Image
    runs-on: ubuntu-latest
    env:
      build_config_name: "ride-vips-adapter-nginx-proxy-build-v2"
      base_image_tag: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
          openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
          namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      - name: Apply Build Yaml
        run: |
          cd rsbc_df_vips_adapter_gateway/github_actions_yamls
          oc process -f revproxy_build_template.yml --param-file revproxy_build_params.yml --param OUTPUT_IMAGE_STREAM_TAG=dev-test-build-$GITHUB_SHA | oc apply -f -
      - name: Start the build and push
        run: |
          oc start-build ${{ env.build_config_name }} --follow --wait

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev
    needs: build-image
    env:
      build_config_name: "ride-vips-adapter-nginx-proxy-build-v2"
      base_image_tag: "1"
      IMAGE_STREAM_TAG: dev-test-build-${{ github.sha}}
    steps:
      - name: Checkout Gitops repository
        uses: actions/checkout@v3
        with:
          repository: bcgov-c/tenant-gitops-be5301
          ref: deployment/rsbc-ride-vips-adapter
          token: ${{ secrets.GITOPS_GITHUB_TOKEN }}
      - name: Update Image tag for Dev deploy
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq eval -i '.images[0].newTag = "${{env.IMAGE_STREAM_TAG}}"' 'ride_vips_adapter/overlays/dev/kustomization.yaml'
      - name: Check Changed value
        run: |
          cat ride_vips_adapter/overlays/dev/kustomization.yaml
      - name: Push Changes to Gitops repo
        run: |
          git add .
          git commit -m "updated dev image details to yaml"
          git push

  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    environment: test
    needs: [build-image,deploy-dev]
    env:
      build_config_name: "ride-vips-adapter-nginx-proxy-build-v2"
      base_image_tag: "1"
      IMAGE_STREAM_TAG: dev-test-build-${{ github.sha}}
    steps:
      - name: Checkout Gitops repository
        uses: actions/checkout@v3
        with:
          repository: bcgov-c/tenant-gitops-be5301
          ref: deployment/rsbc-ride-vips-adapter
          token: ${{ secrets.GITOPS_GITHUB_TOKEN }}
      - name: Update Image tag for Dev deploy
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq eval -i '.images[0].newTag = "${{env.IMAGE_STREAM_TAG}}"' 'ride_vips_adapter/overlays/test/kustomization.yaml'
      - name: Check Changed value
        run: |
          cat ride_vips_adapter/overlays/test/kustomization.yaml
      - name: Push Changes to Gitops repo
        run: |
          git add .
          git commit -m "updated test image details to yaml"
          git push